<Project>
  <PropertyGroup>
    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)\obj\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
    <MSBuildProjectExtensionsPath>$(BaseIntermediateOutputPath)</MSBuildProjectExtensionsPath>
    <BaseOutputPath>$(MSBuildProjectDirectory)\bin\$(MSBuildProjectName)\</BaseOutputPath>
    <DefaultItemExcludes>$(DefaultItemExcludes);bin/**;obj/**;obj_browser/**</DefaultItemExcludes>
  </PropertyGroup>
</Project>
