name: "\U0001F4DA Documentation"
description: Suggest a change or new section to be added to document.
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this issue!
  - type: checkboxes
    id: documentation_is
    attributes:
      label: Documentation is
      options:
        - label: Missing
        - label: Outdated
        - label: Confusing
        - label: Not sure?
  - type: textarea
    id: description
    attributes:
      label: Explain in Detail
      description: A clear and concise description of your suggestion.
      placeholder: The description of ... is not clear. I thought it meant ... but it wasn't.
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Your Suggestion for Changes
    validations:
      required: true