name: "\U0001F680 New feature proposal"
description: Propose a new feature to be added to Sia
labels: [enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your interest in the project and taking the time to fill out this feature report!
  - type: textarea
    id: feature-description
    attributes:
      label: Description
      description: A Clear and concise description of the problem.
      placeholder: As a developer using Sia I want [goal / wish] so that [benefit].
    validations:
      required: true
  - type: textarea
    id: suggested-solution
    attributes:
      label: Suggested solution
      description: In [?] class we could provide following implementation...
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Alternative
      description: A Clear and concise description of any alternative solutions or features you've considered.
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Any other context or screenshots about the feature request here.