namespace Sia.CodeGenerators;

internal partial class SiaBakeEntityGenerator
{
    public static readonly string SiaBakeEntityAttributeName = "Sia.SiaBakeEntityAttribute";
    public static readonly string SiaBakeEntityAttributeSource = $$"""
        // <auto-generated/>
        #nullable enable

        namespace Sia;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(global::System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
        internal sealed class SiaBakeEntityAttribute : global::System.Attribute;
    """;
}