namespace Sia.CodeGenerators;

internal partial class SiaEventsGenerator
{
    public static readonly string SiaEventsAttributeName = "Sia.SiaEventsAttribute";
    public static readonly string SiaEventsAttributeSource =
        $$"""
        // <auto-generated/>
        #nullable enable

        namespace Sia;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(global::System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
        internal sealed class SiaEventsAttribute : global::System.Attribute;
        """;
}