namespace Sia.CodeGenerators;

internal partial class SiaPropertyGenerator
{
    public static readonly string SiaPropertyAttributeName = "Sia.SiaPropertyAttribute";
    public static readonly string SiaPropertyAttributeSource = $$"""
        // <auto-generated/>
        #nullable enable

        namespace Sia;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(
            global::System.AttributeTargets.Property | global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter,
            Inherited = false, AllowMultiple = false)]
        internal sealed class SiaPropertyAttribute : global::System.Attribute
        {
            public string? SetCommand { get; init; }
        }
    """;
}