namespace Sia.CodeGenerators;

using System.Reflection;

internal partial class ComponentPropertyGenerator
{
    public static readonly AssemblyName AssemblyName = typeof(ComponentPropertyGenerator).Assembly.GetName();
    public static readonly string GeneratedCodeAttribute =
        $@"global::System.CodeDom.Compiler.GeneratedCodeAttribute(""{AssemblyName.Name}"", ""{AssemblyName.Version}"")";
    
    public static readonly string SiaPropertyAttributeName = "Sia.SiaPropertyAttribute";

    public static readonly string SiaPropertyAttributeSource = $$"""
        // <auto-generated/>
        #nullable enable

        namespace Sia;

        [{{GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(
            global::System.AttributeTargets.Property | global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter,
            Inherited = false, AllowMultiple = false)]
        internal sealed class SiaPropertyAttribute : global::System.Attribute
        {
            public string? SetCommand { get; init; }
        }
    """;
}