namespace Sia.CodeGenerators;

internal partial class SiaPropertyGenerator
{
    public static readonly string SiaPropertyAttributeName = "Sia.SiaAttribute";
    public static readonly string SiaPropertyAttributeSource =
        $$"""
        // <auto-generated/>
        #nullable enable

        namespace Sia;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(
            global::System.AttributeTargets.Property | global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter,
            Inherited = false, AllowMultiple = false)]
        internal sealed class SiaAttribute : global::System.Attribute
        {
            public bool NoCommands { get; set; } = false;
            public bool InjectContext { get; set; } = false;
            public bool GenerateSetCommand { get; set; } = true;
            public bool GenerateAddItemCommand { get; set; } = true;
            public bool GenerateSetItemCommand { get; set; } = true;
            public bool GenerateRemoveItemCommand { get; set; } = true;

            public string? Item { get; set; } = null;
        }
        """;
}