namespace Sia.CodeGenerators;

using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

[Generator]
public sealed class SiaReactiveArityGenerator : IIncrementalGenerator
{
    private const int MinArity = 1;
    private const int MaxArity = 16;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterSourceOutput(
            context.CompilationProvider.Select(
                static (compilation, _) => compilation.AssemblyName),
            static (production, assemblyName) =>
            {
                if (assemblyName == "Sia.Prelude") {
                    production.AddSource(
                        "SiaReactiveArities.g.cs",
                        SourceText.From(GenerateSource(), Encoding.UTF8));
                }
            });
    }

    private static string GenerateSource()
    {
        var source = new StringBuilder();
        source.AppendLine("// <auto-generated/>");
        source.AppendLine("namespace Sia.Reactive;");
        source.AppendLine();
        source.AppendLine("using System.Runtime.CompilerServices;");
        source.AppendLine();

        for (var arity = MinArity; arity <= MaxArity; arity++) {
            GenerateGroup(source, arity);
        }

        source.AppendLine("public static partial class Term");
        source.AppendLine("{");
        for (var arity = MinArity; arity <= MaxArity; arity++) {
            GenerateTermFactory(source, arity);
        }
        source.AppendLine("}");
        source.AppendLine();

        source.AppendLine("public static partial class Reactive");
        source.AppendLine("{");
        for (var arity = MinArity; arity <= MaxArity; arity++) {
            GenerateReactiveFactory(source, arity);
        }
        source.AppendLine("}");
        return source.ToString();
    }

    private static void GenerateGroup(StringBuilder source, int arity)
    {
        var types = TypeList(arity);
        source.Append("public readonly record struct Group<")
            .Append(types)
            .Append(">(")
            .Append(RecordParameterList(arity))
            .AppendLine(")")
            .Append("    : ITerm<Group<")
            .Append(types)
            .AppendLine(">>");
        AppendConstraints(source, arity, "    ");
        source.AppendLine("{");
        source.Append("    public static int SlotCount => ");
        for (var index = 1; index <= arity; index++) {
            if (index > 1) {
                source.Append(" + ");
            }
            source.Append('T').Append(index).Append(".SlotCount");
        }
        source.AppendLine(";");
        source.AppendLine();

        source.Append("    public static void Mount(in Group<")
            .Append(types)
            .AppendLine("> self, ref GraphContext context)")
            .AppendLine("    {");
        for (var index = 1; index <= arity; index++) {
            source.Append("        T").Append(index)
                .Append(".Mount(self.Item").Append(index)
                .AppendLine(", ref context);");
        }
        source.AppendLine("    }");
        source.AppendLine();

        source.Append("    public static void Reconcile(in Group<")
            .Append(types)
            .Append("> previous, in Group<")
            .Append(types)
            .AppendLine("> next, ref GraphContext context)")
            .AppendLine("    {");
        for (var index = 1; index <= arity; index++) {
            source.Append("        T").Append(index)
                .Append(".Reconcile(previous.Item").Append(index)
                .Append(", next.Item").Append(index)
                .AppendLine(", ref context);");
        }
        source.AppendLine("    }");
        source.AppendLine("}");
        source.AppendLine();
    }

    private static void GenerateTermFactory(StringBuilder source, int arity)
    {
        var types = TypeList(arity);
        source.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]")
            .Append("    public static Group<").Append(types)
            .Append("> Group<").Append(types).AppendLine(">(")
            .Append("        ").Append(ParameterList(arity, includeModifier: true))
            .AppendLine(")");
        AppendConstraints(source, arity, "        ");
        source.Append("        => new(").Append(ArgumentList(arity, ".Term", false))
            .AppendLine(");")
            .AppendLine();
    }

    private static void GenerateReactiveFactory(StringBuilder source, int arity)
    {
        var types = TypeList(arity);
        source.AppendLine("    [MethodImpl(MethodImplOptions.AggressiveInlining)]")
            .Append("    public static ReactiveNode<Group<").Append(types)
            .Append(">> Group<").Append(types).AppendLine(">(")
            .Append("        ").Append(NodeParameterList(arity)).AppendLine(")");
        AppendConstraints(source, arity, "        ");
        source.Append("        => new(Term.Group(")
            .Append(ArgumentList(arity, ".Term", true))
            .AppendLine("));")
            .AppendLine();
    }

    private static void AppendConstraints(
        StringBuilder source,
        int arity,
        string indentation)
    {
        for (var index = 1; index <= arity; index++) {
            source.Append(indentation).Append("where T").Append(index)
                .Append(" : struct, ITerm<T").Append(index).AppendLine(">");
        }
    }

    private static string TypeList(int arity)
        => string.Join(", ", Enumerable.Range(1, arity).Select(
            static index => $"T{index}"));

    private static string ParameterList(int arity, bool includeModifier)
        => string.Join(", ", Enumerable.Range(1, arity).Select(index =>
            $"{(includeModifier ? "in " : string.Empty)}T{index} item{index}"));

    private static string RecordParameterList(int arity)
        => string.Join(", ", Enumerable.Range(1, arity).Select(index =>
            $"T{index} Item{index}"));

    private static string NodeParameterList(int arity)
        => string.Join(", ", Enumerable.Range(1, arity).Select(index =>
            $"scoped in ReactiveNode<T{index}> item{index}"));

    private static string ArgumentList(
        int arity,
        string suffix,
        bool useSuffix)
        => string.Join(", ", Enumerable.Range(1, arity).Select(index =>
            $"item{index}{(useSuffix ? suffix : string.Empty)}"));
}
