namespace Sia.CodeGenerators;

internal partial class SiaSystemGenerator
{
    public static readonly string SiaSystemAttributeName = "Sia.SiaSystemAttribute";
    public static readonly string SiaSystemAttributeSource =
        $$"""
        // <auto-generated/>
        #nullable enable

        namespace Sia;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
        internal sealed class SiaSystemAttribute : global::System.Attribute;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        internal sealed class SiaInSetAttribute<TSet> : global::System.Attribute
            where TSet : global::Sia.ISystemSet;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        internal sealed class SiaBeforeAttribute<TSystem> : global::System.Attribute
            where TSystem : global::Sia.ISystem;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        internal sealed class SiaAfterAttribute<TSystem> : global::System.Attribute
            where TSystem : global::Sia.ISystem;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        internal sealed class SiaBeforeSetAttribute<TSet> : global::System.Attribute
            where TSet : global::Sia.ISystemSet;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(global::System.AttributeTargets.Class, Inherited = false, AllowMultiple = true)]
        internal sealed class SiaAfterSetAttribute<TSet> : global::System.Attribute
            where TSet : global::Sia.ISystemSet;
        """;
}
