namespace Sia.CodeGenerators;

internal partial class SiaTemplateGenerator
{
    public static readonly string SiaTemplateAttributeName = "Sia.SiaTemplateAttribute";
    public static readonly string SiaTemplateAttributeSource = $$"""
        // <auto-generated/>
        #nullable enable

        namespace Sia;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(
            global::System.AttributeTargets.Class | global::System.AttributeTargets.Struct,
            Inherited = false, AllowMultiple = false)]
        internal sealed class SiaTemplateAttribute : global::System.Attribute
        {
            public string ComponentName { get; }
            public bool Immutable { get; set; }

            public SiaTemplateAttribute(string componentName)
            {
                ComponentName = componentName;
            }
        }
    """;

    public static readonly string SiaIgnoreAttributeName = "Sia.SiaIgnoreAttribute";
    public static readonly string SiaIgnoreAttributeSource = $$"""
        // <auto-generated/>
        #nullable enable

        namespace Sia;

        [{{Common.GeneratedCodeAttribute}}]
        [global::System.AttributeUsage(
            global::System.AttributeTargets.Property | global::System.AttributeTargets.Field | global::System.AttributeTargets.Parameter,
            Inherited = false, AllowMultiple = false)]
        internal sealed class SiaIgnoreAttribute : global::System.Attribute
        {
        }
    """;
}