namespace Sia.Examples;

using Sia;

public static partial class Example11_RPG
{
    public interface IWeaponDamageProvider
    {
        public float GetDamage(in WeaponMetadata metadata, in EntityRef attacker, in EntityRef target);
    }

    public readonly record struct WeaponMetadata(
        string Name,
        float BaseDamage,
        IWeaponDamageProvider DamageProvider);
    
    public enum MagicType
    {
        Fire,
        Wind,
        Water,
        Earth
    }

    public static class MagicSword
    {
        private class DamageProvider : IWeaponDamageProvider
        {
            public static readonly DamageProvider Instance = new();

            public float GetDamage(in WeaponMetadata metadata, in EntityRef attacker, in EntityRef target)
            {
                float damage = metadata.BaseDamage + Random.Shared.NextSingle() * 10f;

                ref var attackerCharacter = ref attacker.Get<Character>();
                if (attackerCharacter.MP > 10f) {
                    attackerCharacter.MP -= 10f;
                    damage += 20f;
                }

                return damage;
            }
        }

        public readonly record struct Data(
            MagicType MagicType // not used
        );

        public static readonly WeaponMetadata Metadata = new(
            Name: "Magic Sword",
            BaseDamage: 10f,
            DamageProvider: DamageProvider.Instance);

        public static EntityRef Create(World world, MagicType magicType)
            => world.CreateInBucketHost(Tuple.Create(
                Metadata,
                new Data(magicType)
            ));
    }

    public readonly record struct CharacterMetadata(
        string Species,

        float BaseHP,
        float BaseMP,
        float HPGrowthRate,
        float MPGrowthRate,

        float BaseDamage,
        float BaseDefense,
        float DamageGrowthRate,
        float DefenseGrowthRate);
    
    public partial record struct Character(
        [SiaProperty] string Name,
        [SiaProperty] float HP,
        [SiaProperty] float MP,
        [SiaProperty] int Level = 0,
        [SiaProperty] EntityRef? Weapon = null)
    {
        public readonly record struct Damage(EntityRef Attacker) : ICommand
        {
            public void Execute(World world, in EntityRef self)
            {
                float damage;
                float defense;

                try {
                    ref var attackerMeta = ref Attacker.Get<CharacterMetadata>();
                    ref var attackerCharacter = ref Attacker.Get<Character>();
                    damage = attackerMeta.BaseDamage + attackerCharacter.Level * attackerMeta.DamageGrowthRate;

                    if (attackerCharacter.Weapon is EntityRef weapon) {
                        ref var weaponMeta = ref weapon.Get<WeaponMetadata>();
                        damage += weaponMeta.DamageProvider.GetDamage(weaponMeta, Attacker, self);
                    }
                }
                catch {
                    Console.WriteLine("Failed to execute attack command: attacker is not a valid character");
                    return;
                }

                try {
                    ref var selfMeta = ref self.Get<CharacterMetadata>();
                    ref var selfCharacter = ref self.Get<Character>();
                    defense = selfMeta.BaseDefense + selfCharacter.Level * selfMeta.DefenseGrowthRate;

                    float actualDamage = damage - defense;
                    if (actualDamage < 0f) {
                        return;
                    }
                    // SetHP is generated by SiaPropertyGenerator
                    self.Modify(new SetHP(selfCharacter.HP - actualDamage));
                }
                catch {
                    Console.WriteLine("Failed to execute attack command: self is not a valid character");
                    return;
                }
            }
        }
    }

    public class DeadCharacterDestroySystem()
        : SystemBase(
            matcher: Matchers.Of<Character>(),
            trigger: EventUnion.Of<Character.SetHP>())
    {
        public override void Execute(World world, Scheduler scheduler, IEntityQuery query)
        {
            query.ForEach(static entity => {
                ref var character = ref entity.Get<Character>();
                if (character.HP <= 0) {
                    Console.WriteLine(character.Name + " is dead!");
                    entity.Dispose();
                }
            });
        }
    }

    public static class Human
    {
        public static readonly CharacterMetadata Metadata = new(
            Species: "Human",
            BaseHP: 100f,
            BaseMP: 50f,
            HPGrowthRate: 10f,
            MPGrowthRate: 7f,
            BaseDamage: 10f,
            BaseDefense: 6f,
            DamageGrowthRate: 5f,
            DefenseGrowthRate: 4f);

        public static EntityRef Create(World world, string name)
            => world.CreateInBucketHost(Tuple.Create(
                Metadata,
                new Character(
                    Name: name,
                    HP: Metadata.BaseHP,
                    MP: Metadata.BaseMP)
            ));
    }

    public static void Run(World world)
    {
        var scheduler = new Scheduler();

        SystemChain.Empty
            .Add<DeadCharacterDestroySystem>()
            .RegisterTo(world, scheduler);

        var player = Human.Create(world, "Player");
        var enemy = Human.Create(world, "Enemy");

        var magicSword = MagicSword.Create(world, MagicType.Fire);
        player.Character_SetLevel(100);
        player.Character_SetWeapon(magicSword);

        enemy.Modify(new Character.Damage(player));
        scheduler.Tick();
    }
}