<Project Sdk="Microsoft.NET.Sdk.WebAssembly">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0-browser</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PublishTrimmed>false</PublishTrimmed>
    <IsPackable>false</IsPackable>
    <OverrideHtmlAssetPlaceholders>true</OverrideHtmlAssetPlaceholders>
    <WasmBuildNative>true</WasmBuildNative>
    <WasmEnableSIMD>true</WasmEnableSIMD>
    <WasmEnableWebcil>false</WasmEnableWebcil>
    <WasmEnableThreads>true</WasmEnableThreads>
    <EmccExtraLDFlags>-sALLOW_MEMORY_GROWTH -sWASMFS=1</EmccExtraLDFlags>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="obj_desktop\**" />
    <EmbeddedResource Remove="obj_desktop\**" />
    <None Remove="obj_desktop\**" />
  </ItemGroup>

  <ItemGroup>
    <StaticWebAssetFingerprintPattern Include="JS" Pattern="*.js" Expression="#[.{fingerprint}]!" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sia\Sia.csproj" />
    <ProjectReference Include="..\Sia.CodeGenerators\Sia.CodeGenerators.csproj" OutputItemType="Analyzer" />
    <ProjectReference Include="..\Sia.Prelude\Sia.Prelude.csproj" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="*.notebook.xml">
      <LogicalName>%(Filename)%(Extension)</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="AddBrowserNativeModules" BeforeTargets="_GenerateManagedToNative" DependsOnTargets="PrepareForWasmBuildNative">
    <ItemGroup>
      <_WasmPInvokeModules Include="__Internal_emscripten" />
    </ItemGroup>
  </Target>
</Project>
